# ---------------------------------------------------------------------------
# Where R comes from on this cluster. Sourced by run_pipeline.sbatch,
# submit_all.sh and install_dependencies.sbatch, so the install and the jobs
# cannot drift apart -- which is the failure mode this file exists to prevent.
#
# DO NOT EDIT THIS FILE for site settings. It is tracked by git, so a pull or
# a checkout silently reverts your changes -- and the symptom is a job quietly
# using the wrong R or the wrong library.
#
# Put site settings in slurm/env.local.sh instead, which is untracked and
# sourced below if it exists:
#
#   cat > slurm/env.local.sh <<'SETTINGS'
#   R_MODULE=R/4.3.2-gfbf-2023a
#   R_LIBS_USER=/path/on/lab/storage/R/library-R-4.3.2-gfbf-2023a
#   SETTINGS
#
# See slurm/env.local.sh.example.
#
# Values already in the environment win, so a one-off override still works:
#   R_MODULE=R/4.4.0-gfbf-2023b ./slurm/submit_all.sh 7
#
# That also means re-sourcing this file after editing it does NOT pick up the
# change in a shell that already sourced it -- the old exported value wins. To
# see what the file itself says, read it in a clean environment:
#
#   env -u R_MODULE -u R_LIBS_USER bash -c 'source slurm/env.sh; echo "$R_LIBS_USER"'
#
# Submitted jobs are unaffected: they start from the submitting shell, so a
# stale value there does propagate -- unset it or open a new shell after an
# edit.
# ---------------------------------------------------------------------------

# Site settings, from outside the project first and then from inside it, so
# the more specific in-project file wins where both exist.
#
# THE OUT-OF-PROJECT LOCATION IS THE IMPORTANT ONE. slurm/env.local.sh lives
# in the working copy, so it survives a git pull but NOT re-downloading the
# repository as an archive -- and a rebuilt working copy with no site settings
# does not fail loudly. It falls back to $HOME for the library, finds no
# packages there, and every job dies on "missing packages: Seurat, Matrix,
# dplyr, ..." as though nothing were ever installed.
#
# Keep the real settings at ~/.config/bm-aging/env.sh (or point BM_AGING_ENV
# at them) and they outlive any number of fresh downloads.
# What the environment already held. The settings files use plain assignments,
# which overwrite an exported value, so a one-off override on the command line
# would otherwise be silently ignored -- contrary to what this file documents
# above. Captured here and put back after sourcing.
_pre_R_MODULE="${R_MODULE:-}"
_pre_R_LIBS_USER="${R_LIBS_USER:-}"
_pre_GITHUB_PAT="${GITHUB_PAT:-}"
_pre_CRAN_SNAPSHOT="${CRAN_SNAPSHOT:-}"

_env_dir="$(cd "$(dirname "${BASH_SOURCE[0]:-slurm/env.sh}")" && pwd)"
_env_found=""
for _candidate in "${BM_AGING_ENV:-}" \
                  "$HOME/.config/bm-aging/env.sh" \
                  "$HOME/.bm-aging-env.sh" \
                  "$_env_dir/env.local.sh"; do
  if [[ -n "$_candidate" && -f "$_candidate" ]]; then
    # shellcheck disable=SC1090
    source "$_candidate"
    _env_found="${_env_found}${_env_found:+, }$_candidate"
  fi
done

if [[ -z "$_env_found" ]]; then
  cat >&2 <<'MSG'

WARNING: no site settings file found. Looked at, in order:
  $BM_AGING_ENV, ~/.config/bm-aging/env.sh, ~/.bm-aging-env.sh,
  slurm/env.local.sh

R_MODULE and R_LIBS_USER will fall back to defaults that are almost certainly
wrong for this cluster, and jobs will fail with "missing packages: Seurat,
Matrix, dplyr, ..." -- which reads as an install problem and is not one.

  mkdir -p ~/.config/bm-aging
  cp slurm/env.local.sh.example ~/.config/bm-aging/env.sh
  # then edit it

That location is outside the project, so re-downloading the repository cannot
remove it.

MSG
else
  echo "site settings: $_env_found" >&2
fi
unset _env_dir _env_found _candidate

# Restore anything the caller set explicitly; it outranks every file.
[[ -n "$_pre_R_MODULE"     ]] && R_MODULE="$_pre_R_MODULE"
[[ -n "$_pre_R_LIBS_USER"  ]] && R_LIBS_USER="$_pre_R_LIBS_USER"
[[ -n "$_pre_GITHUB_PAT"   ]] && GITHUB_PAT="$_pre_GITHUB_PAT"
[[ -n "$_pre_CRAN_SNAPSHOT" ]] && CRAN_SNAPSHOT="$_pre_CRAN_SNAPSHOT"
unset _pre_R_MODULE _pre_R_LIBS_USER _pre_GITHUB_PAT _pre_CRAN_SNAPSHOT

# Environment module(s) providing R, space-separated. Several packages need
# system libraries that EasyBuild ships as their own modules -- sf needs GDAL,
# GEOS and PROJ; ragg needs libwebp, freetype and harfbuzz -- and monocle3
# needs sf. Find them with:
#   module -t avail | grep -iE '^(GDAL|GEOS|PROJ|UDUNITS|libwebp|freetype)/'
# Leave empty if R is already on PATH (e.g. an activated conda environment).
R_MODULE="${R_MODULE:-R/4.3.2-gfbf-2023a}"

# Where the pipeline's own packages live. Two requirements:
#   - on a filesystem the compute nodes can see (NOT a node-local /tmp, and on
#     some clusters not $HOME either);
#   - versioned by R release, so switching modules does not mix incompatible
#     builds in one directory.
#
# $HOME is the default but is often the wrong choice: home quotas are small and
# this library runs to several GB. Prefer group or lab storage, e.g.
#   R_LIBS_USER="${R_LIBS_USER:-/nemo/lab/<lab>/home/users/<user>/R/library-${R_MODULE//\//-}}"
R_LIBS_USER="${R_LIBS_USER:-$HOME/R/library-${R_MODULE//\//-}}"

export R_MODULE R_LIBS_USER

# A GitHub token, if one was set in env.local.sh. Exported so R's remotes
# package can see it -- a plain assignment there is a shell variable only.
# It raises the GitHub API limit from 60 requests per hour per IP (shared with
# every other user of this cluster) to 5000 per hour for you alone.
[[ -n "${GITHUB_PAT:-}" ]] && export GITHUB_PAT

# A dated CRAN snapshot used as a fallback repository when current CRAN carries
# only versions that need a newer R than this one.
[[ -n "${CRAN_SNAPSHOT:-}" ]] && export CRAN_SNAPSHOT

# ---------------------------------------------------------------------------
# Ignore personal R startup files for pipeline runs.
#
# ~/.Renviron, ~/.Rprofile and ~/.R/Makevars are read by every R session and
# override the environment the job sets up. On a cluster with several R
# versions that reliably goes wrong:
#
#   - an R_LIBS_USER pinned to another R version's library, so packages
#     install into (and load from) a tree built for a different R. The
#     symptoms are "This is R 4.3.2, package 'Matrix' needs >= 4.4",
#     "unable to load shared object .../libs/foo.so", and "failed to lock
#     directory ... for modifying";
#   - a Makevars adding a conda prefix to CPPFLAGS/LDFLAGS, so packages
#     compile against conda headers and link conda libraries while running
#     under a module R. That is what produces a dyn.load of a conda
#     libstdc++ from an R that has nothing to do with conda.
#
# This affects pipeline runs only; interactive R still reads them normally.
# Set CLEAN_R_STARTUP= (empty) to opt out.
CLEAN_R_STARTUP="${CLEAN_R_STARTUP:-1}"
if [[ -n "$CLEAN_R_STARTUP" ]]; then
  export R_ENVIRON_USER=/dev/null
  export R_PROFILE_USER=/dev/null
  export R_MAKEVARS_USER=/dev/null
  # R_LIBS would prepend other trees ahead of R_LIBS_USER.
  unset R_LIBS || true
fi
